# Generated by Django 3.1.7 on 2021-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
